In [2]:
import numpy as np

# 4.3.3 偏微分

In [3]:
def function_2(x):
    return np.sum(x**2)

# 4.4 勾配

In [10]:
def numerical_gradient(f , x):
    h = np.exp(-4)
    grad = np.zeros_like(x)  # x と同じ形状の配列を生成する
    
    for idx in range(x.size):
        tmp_val = x[idx]
        
        # f(x+h)の計算
        x[idx] = tmp_val + h
        fxh1 = f(x)
        
        # f(x+h)の計算
        x[idx] = tmp_val - h
        fxh2 = f(x)
        
        grad[idx] = (fxh1 - fxh2)  / (2*h)
        x[idx] = tmp_val   # 値を元に戻す
    
    return grad

In [15]:
a = np.array([3.0 , 4.0])
numerical_gradient(function_2 , a)

array([6., 8.])

In [16]:
b = np.array([0.0 , 2.0])
numerical_gradient(function_2 , b)

array([0., 4.])

In [17]:
def gradient_descent(f , init_x , lr=0.01 , step_num=100):
    x = init_x
    
    for i in range(step_num):
        grad = numerical_gradient(f , x)
        x -= lr * grad
    return x

In [18]:
def function_2(x):
    return x[0]**2 + x[1]**2

In [20]:
init_x = np.array([-3.0 , 4.0])
gradient_descent(function_2 , init_x=init_x , lr=0.1 , step_num=100)

array([-6.11110793e-10,  8.14814390e-10])

In [23]:
init_x = np.array([-3.0 , 4.0])
gradient_descent(function_2 , init_x=init_x , lr=10 , step_num=100)

array([ 3.94190998e+14, -5.00769798e+14])

In [25]:
init_x = np.array([-3.0 , 4.0])
gradient_descent(function_2 , init_x=init_x , lr=np.exp(-10) , step_num=100)

array([-2.97288211,  3.96384282])