# 1.5.1　Numpyのインポート

In [2]:
import numpy as np

# 1.5.2 Numpy配列の生成

In [4]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [5]:
type(x)

numpy.ndarray

# 1.5.3 Numpyの算術計算

In [10]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [11]:
x + y

array([3., 6., 9.])

In [12]:
x - y

array([-1., -2., -3.])

In [13]:
x * y

array([ 2.,  8., 18.])

In [14]:
x / y

array([0.5, 0.5, 0.5])

In [17]:
x = np.array([1.0, 2.0, 3.0])
x /2.0

array([0.5, 1. , 1.5])

# 1.5.4 NumpyのＮ次元配列

In [16]:
A = np.array([[1, 2] , [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [18]:
A.shape

(2, 2)

In [19]:
A.dtype

dtype('int32')

In [20]:
B = np.array([[3, 0] , [0 ,6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [21]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [22]:
print(A)

[[1 2]
 [3 4]]


In [23]:
A * 10

array([[10, 20],
       [30, 40]])