# 1.5.1　Numpyのインポート

In [2]:
import numpy as np

# 1.5.2 Numpy配列の生成

In [4]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [5]:
type(x)

numpy.ndarray

# 1.5.3 Numpyの算術計算

In [10]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [11]:
x + y

array([3., 6., 9.])

In [12]:
x - y

array([-1., -2., -3.])

In [13]:
x * y

array([ 2.,  8., 18.])

In [14]:
x / y

array([0.5, 0.5, 0.5])

In [17]:
x = np.array([1.0, 2.0, 3.0])
x /2.0

array([0.5, 1. , 1.5])

# 1.5.4 NumpyのＮ次元配列

In [16]:
A = np.array([[1, 2] , [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [18]:
A.shape

(2, 2)

In [19]:
A.dtype

dtype('int32')

In [20]:
B = np.array([[3, 0] , [0 ,6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [21]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [22]:
print(A)

[[1 2]
 [3 4]]


In [23]:
A * 10

array([[10, 20],
       [30, 40]])

# 1.5.5

In [3]:
import numpy as np
A = np.array([[1,2], [3,4]])
B = np.array([10,20])
A * B

array([[10, 40],
       [30, 80]])

# 1.5.6

In [4]:
X = np.array([[51,55] , [14,19] ,[0,4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [11]:
# 0行目
X[0]

array([51, 55])

In [12]:
# 0行目１列目
X[0][1]

55

In [13]:
# 行毎に繰り返し
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [17]:
# １次元配列に変換
X = X.flatten()
print(X)


[51 55 14 19  0  4]


In [18]:
# インデックスが０、２、４番目の要素を取得
X[np.array([0 ,2, 4])]

array([51, 14,  0])

In [19]:
X > 15

array([ True,  True, False,  True, False, False])

In [20]:
X[X > 15]

array([51, 55, 19])